# Configuración corregida para el proyecto Libruarys
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Cambiado de vacío a ROOT según tu acceso en Workbench
spring.datasource.password=ROOT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Validación de esquema existente
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect